#!/bin/sh
# An empty fresh ubuntu with the artifacts mounted to test installation.
docker run \
    --name test-deb \
    --rm \
    -it \
    -v ~/ned-build/artifacts:/root/artifacts \
    test-deb \
    /bin/bash -c \
        'dpkg -i ned_*-1_amd64.deb &&
         man ned | ned -q "ned.*Powerful" &&
         printf "\e[32mDeb OK\e[0m\n" && exit 0
         printf "\e[31mDeb FAILED\e[0m\n" && exit 1'
