#!/bin/sh
# An empty fresh ubuntu with the artifacts mounted to test installation.
docker container rm text-deb
docker run \
    -it \
    -v ~/ned-build/artifacts:/root/artifacts
    --name test-deb \
    test-deb \
    /bin/bash
